# Generated by Django 2.0.13 on 2019-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='breed',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of Breed'),
        ),
    ]
